<?xml version="1.0"?>

<robot name="test cylinder" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
  <xacro:property name="mass" value="0.01" />
  <xacro:property name="length" value="1" /> 
  <xacro:property name="width" value="0.01" /> 
  <xacro:property name="height" value="1" /> 
  <xacro:property name="radius" value="0.1" /> 

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/testcylinder.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="cylinder"/>
  </joint>

    <link name="cylinder">
      <visual>
        <origin xyz="0.001875 -0.3 ${height/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length ="${length}" radius = "${radius}"/>
        </geometry>
        <material name="gray"><color rgba="0.5 0.5 0.9 0.5"/></material>
      </visual>
      <collision>
        <origin xyz="0.001875 -0.3 ${height/2}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length ="${length}" radius = "${radius}"/>
        </geometry>
      </collision>
    <inertial>
      <mass value="1000"/>
      <inertia 	  
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
    </link>

</robot>

